### ISSUE TITLE
All travis tests broken since Mar 23

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.traversing#14]
See https://travis-ci.org/github/zopefoundation/zope.traversing/builds/665832558

New dependencies include zope.interface 5 and others.

**Comment by mgedmin** [comment]
I can reproduce with `tox`: 4 failures on Python 2.7, 3 failures on others (one of the failing tests is about old-style classes).

`.tox/py37/bin/pip install "zope.interface<5.0" "zope.schema<6.0"` makes the failures go away (same on py27).  Downgrading just zope.schema is not sufficient; downgrading just zope.interface is not something I've tried since zope.schema 6.0 requires zope.interface >= 5.0.

The failing tests are 
```
Error in test testComplexPath (zope.traversing.tests.test_publicationtraverse.TestPublicationTraverser)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/mg/src/zopefoundation/zope.traversing/src/zope/traversing/tests/test_publicationtraverse.py", line 107, in testComplexPath
    proxy = t.traversePath(request, ob, 'foo/../alpha//beta/./bar')
  File "/home/mg/src/zopefoundation/zope.traversing/src/zope/traversing/publicationtraverse.py", line 107, in traversePath
    ob = self.traverseName(request, ob, name)
  File "/home/mg/src/zopefoundation/zope.traversing/src/zope/traversing/publicationtraverse.py", line 77, in traverseName
    raise NotFound(ob, name, request)
NotFound: Object: <zope.traversing.tests.test_publicationtraverse.View object at 0x7f21377c5910>, name: ''



Error in test testPathFound (zope.traversing.tests.test_publicationtraverse.TestPublicationTraverser)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/mg/src/zopefoundation/zope.traversing/src/zope/traversing/tests/test_publicationtraverse.py", line 95, in testPathFound
    proxy = t.traversePath(request, ob, 'foo/bar')
  File "/home/mg/src/zopefoundation/zope.traversing/src/zope/traversing/publicationtraverse.py", line 107, in traversePath
    ob = self.traverseName(request, ob, name)
  File "/home/mg/src/zopefoundation/zope.traversing/src/zope/traversing/publicationtraverse.py", line 77, in traverseName
    raise NotFound(ob, name, request)
NotFound: Object: <zope.traversing.tests.test_publicationtraverse.View object at 0x7f213794e990>, name: 'bar'



Error in test testTraverseRelativeURL (zope.traversing.tests.test_publicationtraverse.TestPublicationTraverser)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/mg/src/zopefoundation/zope.traversing/src/zope/traversing/tests/test_publicationtraverse.py", line 122, in testTraverseRelativeURL
    proxy = t.traverseRelativeURL(request, ob, 'foo/bar')
  File "/home/mg/src/zopefoundation/zope.traversing/src/zope/traversing/publicationtraverse.py", line 113, in traverseRelativeURL
    ob = self.traversePath(request, ob, path)
  File "/home/mg/src/zopefoundation/zope.traversing/src/zope/traversing/publicationtraverse.py", line 107, in traversePath
    ob = self.traverseName(request, ob, name)
  File "/home/mg/src/zopefoundation/zope.traversing/src/zope/traversing/publicationtraverse.py", line 77, in traverseName
    raise NotFound(ob, name, request)
NotFound: Object: <zope.traversing.tests.test_publicationtraverse.View object at 0x7f213777b210>, name: 'bar'



Error in test testTraverseOldStyleClass (zope.traversing.tests.test_traverser.UnrestrictedTraverseTests)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/mg/src/zopefoundation/zope.traversing/src/zope/traversing/tests/test_traverser.py", line 145, in testTraverseOldStyleClass
    self.assertTrue(tr.traverse('theclass/x') is AnOldStyleClass.x)
  File "/home/mg/src/zopefoundation/zope.traversing/src/zope/traversing/adapters.py", line 100, in traverse
    curr = traversePathElement(curr, name, path, request=request)
  File "/home/mg/src/zopefoundation/zope.traversing/src/zope/traversing/adapters.py", line 153, in traversePathElement
    raise LocationError('No traversable adapter found', obj)
   - __traceback_info__: (<class zope.traversing.tests.test_traverser.AnOldStyleClass at 0x7f213783ab40>, 'x')
LocationError: ('No traversable adapter found', <class zope.traversing.tests.test_traverser.AnOldStyleClass at 0x7f213783ab40>)
```

**Comment by mgedmin** [comment]
Focusing on just one of the errors, the test setup does

```python
        zope.component.provideAdapter(DefaultTraversable, (None,), ITraversable)
```

and then the code does

```python
        traversable = ITraversable(obj, None)
        if traversable is None:
            raise LocationError('No traversable adapter found', obj)
```

and raises the LocationError because traversable is None.

This is wrong, since an adapter registered for None is supposed to be able to adapt anything at all, so traversable should be an instance of DefaultTraversable.

Note that changing the setup code to do

```python
        from zope.interface import Interface
        zope.component.provideAdapter(DefaultTraversable, (Interface,), ITraversable)
```

doesn't make the error go away.

**Comment by jamadden** [comment]
> downgrading just zope.interface is not something I've tried 

I have. The issue is something in `zope.interface` 5. I'm working on tracking it down. It doesn't appear to be a change in the IRO (setting 'USE_LEGACY_IRO' makes no change). It doesn't appear to be because `Interface` moved in the resolution order (leaving it where it was before doesn't change things).

**Comment by mgedmin** [comment]
Hm, changing 

```python
        class AnOldStyleClass:
```

to

```python
        class AnOldStyleClass(object):
```

makes the error I was focusing on disappear.  So something changed about old-style class handling!

Note that the lookup is done _on the class itself_, not on an instance.  Keeping AnOldStyleClass old-style and changing the test to use an instance with

```diff
--- a/src/zope/traversing/tests/test_traverser.py
+++ b/src/zope/traversing/tests/test_traverser.py
@@ -139,7 +139,7 @@ class UnrestrictedTraverseTests(PlacelessSetup, unittest.TestCase):
         class AnOldStyleClass:
             x = object()
         container = {}
-        container['theclass'] = AnOldStyleClass
+        container['theclass'] = AnOldStyleClass()
 
         tr = Traverser(container)
         self.assertTrue(tr.traverse('theclass/x') is AnOldStyleClass.x)
```

*also* makes the error go away.

**Comment by jamadden** [comment]
I'm looking at `test_complexPath`. It doesn't have any old-style classes involved, but it does have an instance of `View(object)` that doesn't implement anything, so it gets an instance of `_ImmutableDeclaration` for its `providedBy`. Flattening that reveals `[]`. I'm wondering if that used to include `Interface`...

**Comment by mgedmin** [comment]
The other three errors are about this adapter:

```python
        provideAdapter(DummyPublishTraverse, (Interface, Interface),
                       IPublishTraverse)
```

not being found by 

```python
            # self is marker
            adapter = queryMultiAdapter((ob, request), IPublishTraverse,
                                        default=self)
```

Again, that shouldn't be possible, because a multi-adapter on (Interface, Interface) is supposed to match any possible values of (ob, request).

**Comment by jamadden** [comment]
> I'm wondering if that used to include Interface…

Yes, that's exactly it. The `_empty` singleton in zope.interface 4.7 flattens to `[Interface]`, while in 5.0 it does not. That probably explains both issues.

**Comment by mgedmin** [comment]
```diff
--- a/src/zope/traversing/tests/test_publicationtraverse.py
+++ b/src/zope/traversing/tests/test_publicationtraverse.py
@@ -211,6 +211,7 @@ class IContent(Interface):
 class Content(object):
     pass
 
+@implementer(Interface)
 class View(object):
     def __init__(self, name):
         self.name = name
```

makes the other three errors go away, so I think you're on the right path!

**Comment by jamadden** [comment]
Yup, if I change 5.0 to include `Interface` in `_empty`, all issues are fixed. 

Ok, so I need to go back to zope.interface and make a patch there. Interesting there was no test there for that (and also no test failures in the Plone test suite!).

Thanks for the help!

**Comment by jamadden** [comment]
Build with zope.interface 5.0.2 is [green again](https://travis-ci.org/github/zopefoundation/zope.traversing/builds/668719084).
